version: '3'
services:
  php:
    image: abtercms/php:latest
    volumes:
      - .:/website
    working_dir: /website
    restart: always
    ports:
      - "8023:8023"
    command: php -S 0.0.0.0:8023
    env_file:
      - .env
